export const mockRevealItems = [
  {
    id: "1",
    imageUrl: "/assets/reveal/blastoise-piplup.jpg",
    title: "2019 Cosmic Eclipse Blastoise & Piplup GX #253 PSA 9",
    swapPrice: 250,
    isSelected: false,
    isSwapped: false,
  },
  {
    id: "2",
    imageUrl: "/assets/reveal/blastoise-piplup.jpg",
    title: "2019 Cosmic Eclipse Blastoise & Piplup GX #253 PSA 9",
    swapPrice: 250,
    isSelected: false,
    isSwapped: false,
  },
  {
    id: "3",
    imageUrl: "/assets/reveal/blastoise-piplup.jpg",
    title: "2019 Cosmic Eclipse Blastoise & Piplup GX #253 PSA 9",
    swapPrice: 250,
    isSelected: false,
    isSwapped: false,
  },
  {
    id: "4",
    imageUrl: "/assets/reveal/blastoise-piplup.jpg",
    title: "2019 Cosmic Eclipse Blastoise & Piplup GX #253 PSA 9",
    swapPrice: 250,
    isSelected: false,
    isSwapped: false,
  },
  {
    id: "5",
    imageUrl: "/assets/reveal/blastoise-piplup.jpg",
    title: "2019 Cosmic Eclipse Blastoise & Piplup GX #253 PSA 9",
    swapPrice: 250,
    isSelected: false,
    isSwapped: false,
  },
  {
    id: "6",
    imageUrl: "/assets/reveal/blastoise-piplup.jpg",
    title: "2019 Cosmic Eclipse Blastoise & Piplup GX #253 PSA 9",
    swapPrice: 250,
    isSelected: false,
    isSwapped: false,
  },
  {
    id: "7",
    imageUrl: "/assets/reveal/blastoise-piplup.jpg",
    title: "2019 Cosmic Eclipse Blastoise & Piplup GX #253 PSA 9",
    swapPrice: 250,
    isSelected: false,
    isSwapped: false,
  },
  {
    id: "8",
    imageUrl: "/assets/reveal/blastoise-piplup.jpg",
    title: "2019 Cosmic Eclipse Blastoise & Piplup GX #253 PSA 9",
    swapPrice: 250,
    isSelected: false,
    isSwapped: false,
  },
  {
    id: "9",
    imageUrl: "/assets/reveal/blastoise-piplup.jpg",
    title: "2019 Cosmic Eclipse Blastoise & Piplup GX #253 PSA 9",
    swapPrice: 250,
    isSelected: false,
    isSwapped: false,
  },
  {
    id: "10",
    imageUrl: "/assets/reveal/blastoise-piplup.jpg",
    title: "2019 Cosmic Eclipse Blastoise & Piplup GX #253 PSA 9",
    swapPrice: 250,
    isSelected: false,
    isSwapped: false,
  },
];
